# CI
# 
# Doesn't build on Windows due to libclang.dll not being found.
#
# Interesting links:
# - https://github.com/rust-lang/rust-bindgen/issues/1797
# - https://github.com/KyleMayes/clang-sys#environment-variables
# - https://stackoverflow.com/a/51312174
# - https://stackoverflow.com/questions/59316239/what-is-the-official-way-to-access-the-visual-studio-2019-version-of-clang-from
# 
# Sketch for possible workaround:
# (new-object System.Net.WebClient).DownloadFile('https://ziglang.org/deps/llvm%2bclang%2blld-10.0.0-x86_64-windows-msvc-release-mt.tar.xz','D:\llvm.tar.xz’)
# TODO: unpack archive, extract file
# $env:LIBCLANG_PATH = "D:\libclang.dll"
# 

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies (Linux)
      run: |
        sudo apt update
        sudo apt install cmake git
      if: contains(matrix.os, 'ubuntu')

    - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
      uses: KyleMayes/install-llvm-action@32c4866ebb71e0949e8833eb49beeebed48532bd
      if: contains(matrix.os, 'windows')
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      if: contains(matrix.os, 'windows')
    - name: Download sleef-sys
      run: git submodule update --init
    - name: Install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      run: cargo +nightly build --release --features "static" --verbose
    - name: Run tests
      run: cargo +nightly test --release --features "static" --verbose
